services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KC_VERSION}
    command:
      - "start-dev"
      - "--import-realm"
      - "--spi-theme-static-max-age=-1"
      - "--spi-theme-cache-themes=false"
      - "--spi-theme-cache-templates=false"
    restart: unless-stopped
    environment:
      KC_LOG_LEVEL: ${KC_LOG_LEVEL}
      KC_REALM_NAME: ${KC_REALM_NAME}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      # KC_DB: postgres
      # KC_DB_URL: jdbc:postgresql://127.0.0.1:5432/keycloak
      # KC_DB_USERNAME: ${KC_DB_USERNAME}
      # KC_DB_PASSWORD: ${KC_DB_PASSWORD}
    ports:
      - ${KC_PORT}:8080
    volumes:
      - ./.docker/keycloak-config/:/opt/keycloak/data/import/:ro
      - ./themes/:/opt/keycloak/themes/lnfoot-auth-theme:ro